---
- name: openwakeword
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: "Install pip dependencies"
      ansible.builtin.pip:
        name: openwakeword
        version: 0.5.1
        executable: pip3
